// <auto-generated />
using System;
using CineViet.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250509104602_AddStatusToBooking")]
    partial class AddStatusToBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShowtimeId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("WebApplication2.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Nguyễn Văn Linh, Q7",
                            Name = "CineViet Quận 7"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Lê Lợi, Q1",
                            Name = "CineViet Quận 1"
                        });
                });

            modelBuilder.Entity("WebApplication2.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 181,
                            Genre = "Hành động, Phiêu lưu",
                            Image = "/images/avengers.jpg",
                            Name = "Avengers: Endgame",
                            Rating = 9.1999999999999993,
                            Status = "now",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            Duration = 122,
                            Genre = "Tội phạm, Kịch tính",
                            Image = "/images/joker.jpg",
                            Name = "Joker",
                            Rating = 8.4000000000000004,
                            Status = "now",
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Duration = 132,
                            Genre = "Hài kịch, Kịch tính",
                            Image = "/images/parasite.jpg",
                            Name = "Parasite",
                            Rating = 8.5999999999999996,
                            Status = "now",
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            Duration = 176,
                            Genre = "Hành động, Tội phạm",
                            Image = "/images/batman.jpg",
                            Name = "The Batman",
                            Rating = 7.9000000000000004,
                            Status = "coming",
                            Year = 2024
                        },
                        new
                        {
                            Id = 5,
                            Duration = 155,
                            Genre = "Phiêu lưu, Khoa học viễn tưởng",
                            Image = "/images/dune.jpg",
                            Name = "Dune",
                            Rating = 8.0999999999999996,
                            Status = "coming",
                            Year = 2024
                        },
                        new
                        {
                            Id = 6,
                            Duration = 163,
                            Genre = "Hành động, Phiêu lưu",
                            Image = "/images/notimetodie.jpg",
                            Name = "No Time to Die",
                            Rating = 7.7000000000000002,
                            Status = "coming",
                            Year = 2024
                        },
                        new
                        {
                            Id = 7,
                            Duration = 148,
                            Genre = "Hành động, Phiêu lưu",
                            Image = "/images/spiderman.jpg",
                            Name = "Spider-Man: No Way Home",
                            Rating = 8.3000000000000007,
                            Status = "coming",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("WebApplication2.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVip")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 1,
                            Row = "A"
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 2,
                            Row = "A"
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 3,
                            Row = "A"
                        },
                        new
                        {
                            Id = 4,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 4,
                            Row = "A"
                        },
                        new
                        {
                            Id = 5,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 5,
                            Row = "A"
                        },
                        new
                        {
                            Id = 6,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 6,
                            Row = "A"
                        },
                        new
                        {
                            Id = 7,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 7,
                            Row = "A"
                        },
                        new
                        {
                            Id = 8,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 8,
                            Row = "A"
                        },
                        new
                        {
                            Id = 9,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 1,
                            Row = "B"
                        },
                        new
                        {
                            Id = 10,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 2,
                            Row = "B"
                        },
                        new
                        {
                            Id = 11,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 3,
                            Row = "B"
                        },
                        new
                        {
                            Id = 12,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 4,
                            Row = "B"
                        },
                        new
                        {
                            Id = 13,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 5,
                            Row = "B"
                        },
                        new
                        {
                            Id = 14,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 6,
                            Row = "B"
                        },
                        new
                        {
                            Id = 15,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 7,
                            Row = "B"
                        },
                        new
                        {
                            Id = 16,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 8,
                            Row = "B"
                        },
                        new
                        {
                            Id = 17,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 1,
                            Row = "C"
                        },
                        new
                        {
                            Id = 18,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 2,
                            Row = "C"
                        },
                        new
                        {
                            Id = 19,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 3,
                            Row = "C"
                        },
                        new
                        {
                            Id = 20,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 4,
                            Row = "C"
                        },
                        new
                        {
                            Id = 21,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 5,
                            Row = "C"
                        },
                        new
                        {
                            Id = 22,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 6,
                            Row = "C"
                        },
                        new
                        {
                            Id = 23,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 7,
                            Row = "C"
                        },
                        new
                        {
                            Id = 24,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 8,
                            Row = "C"
                        },
                        new
                        {
                            Id = 25,
                            CinemaId = 1,
                            IsVip = true,
                            Number = 1,
                            Row = "D"
                        },
                        new
                        {
                            Id = 26,
                            CinemaId = 1,
                            IsVip = true,
                            Number = 2,
                            Row = "D"
                        },
                        new
                        {
                            Id = 27,
                            CinemaId = 1,
                            IsVip = true,
                            Number = 3,
                            Row = "D"
                        },
                        new
                        {
                            Id = 28,
                            CinemaId = 1,
                            IsVip = true,
                            Number = 4,
                            Row = "D"
                        },
                        new
                        {
                            Id = 29,
                            CinemaId = 1,
                            IsVip = true,
                            Number = 5,
                            Row = "D"
                        },
                        new
                        {
                            Id = 30,
                            CinemaId = 1,
                            IsVip = true,
                            Number = 6,
                            Row = "D"
                        },
                        new
                        {
                            Id = 31,
                            CinemaId = 1,
                            IsVip = true,
                            Number = 7,
                            Row = "D"
                        },
                        new
                        {
                            Id = 32,
                            CinemaId = 1,
                            IsVip = true,
                            Number = 8,
                            Row = "D"
                        },
                        new
                        {
                            Id = 33,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 1,
                            Row = "E"
                        },
                        new
                        {
                            Id = 34,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 2,
                            Row = "E"
                        },
                        new
                        {
                            Id = 35,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 3,
                            Row = "E"
                        },
                        new
                        {
                            Id = 36,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 4,
                            Row = "E"
                        },
                        new
                        {
                            Id = 37,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 5,
                            Row = "E"
                        },
                        new
                        {
                            Id = 38,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 6,
                            Row = "E"
                        },
                        new
                        {
                            Id = 39,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 7,
                            Row = "E"
                        },
                        new
                        {
                            Id = 40,
                            CinemaId = 1,
                            IsVip = false,
                            Number = 8,
                            Row = "E"
                        },
                        new
                        {
                            Id = 41,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 1,
                            Row = "A"
                        },
                        new
                        {
                            Id = 42,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 2,
                            Row = "A"
                        },
                        new
                        {
                            Id = 43,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 3,
                            Row = "A"
                        },
                        new
                        {
                            Id = 44,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 4,
                            Row = "A"
                        },
                        new
                        {
                            Id = 45,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 5,
                            Row = "A"
                        },
                        new
                        {
                            Id = 46,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 6,
                            Row = "A"
                        },
                        new
                        {
                            Id = 47,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 7,
                            Row = "A"
                        },
                        new
                        {
                            Id = 48,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 8,
                            Row = "A"
                        },
                        new
                        {
                            Id = 49,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 1,
                            Row = "B"
                        },
                        new
                        {
                            Id = 50,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 2,
                            Row = "B"
                        },
                        new
                        {
                            Id = 51,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 3,
                            Row = "B"
                        },
                        new
                        {
                            Id = 52,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 4,
                            Row = "B"
                        },
                        new
                        {
                            Id = 53,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 5,
                            Row = "B"
                        },
                        new
                        {
                            Id = 54,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 6,
                            Row = "B"
                        },
                        new
                        {
                            Id = 55,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 7,
                            Row = "B"
                        },
                        new
                        {
                            Id = 56,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 8,
                            Row = "B"
                        },
                        new
                        {
                            Id = 57,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 1,
                            Row = "C"
                        },
                        new
                        {
                            Id = 58,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 2,
                            Row = "C"
                        },
                        new
                        {
                            Id = 59,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 3,
                            Row = "C"
                        },
                        new
                        {
                            Id = 60,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 4,
                            Row = "C"
                        },
                        new
                        {
                            Id = 61,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 5,
                            Row = "C"
                        },
                        new
                        {
                            Id = 62,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 6,
                            Row = "C"
                        },
                        new
                        {
                            Id = 63,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 7,
                            Row = "C"
                        },
                        new
                        {
                            Id = 64,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 8,
                            Row = "C"
                        },
                        new
                        {
                            Id = 65,
                            CinemaId = 2,
                            IsVip = true,
                            Number = 1,
                            Row = "D"
                        },
                        new
                        {
                            Id = 66,
                            CinemaId = 2,
                            IsVip = true,
                            Number = 2,
                            Row = "D"
                        },
                        new
                        {
                            Id = 67,
                            CinemaId = 2,
                            IsVip = true,
                            Number = 3,
                            Row = "D"
                        },
                        new
                        {
                            Id = 68,
                            CinemaId = 2,
                            IsVip = true,
                            Number = 4,
                            Row = "D"
                        },
                        new
                        {
                            Id = 69,
                            CinemaId = 2,
                            IsVip = true,
                            Number = 5,
                            Row = "D"
                        },
                        new
                        {
                            Id = 70,
                            CinemaId = 2,
                            IsVip = true,
                            Number = 6,
                            Row = "D"
                        },
                        new
                        {
                            Id = 71,
                            CinemaId = 2,
                            IsVip = true,
                            Number = 7,
                            Row = "D"
                        },
                        new
                        {
                            Id = 72,
                            CinemaId = 2,
                            IsVip = true,
                            Number = 8,
                            Row = "D"
                        },
                        new
                        {
                            Id = 73,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 1,
                            Row = "E"
                        },
                        new
                        {
                            Id = 74,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 2,
                            Row = "E"
                        },
                        new
                        {
                            Id = 75,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 3,
                            Row = "E"
                        },
                        new
                        {
                            Id = 76,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 4,
                            Row = "E"
                        },
                        new
                        {
                            Id = 77,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 5,
                            Row = "E"
                        },
                        new
                        {
                            Id = 78,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 6,
                            Row = "E"
                        },
                        new
                        {
                            Id = 79,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 7,
                            Row = "E"
                        },
                        new
                        {
                            Id = 80,
                            CinemaId = 2,
                            IsVip = false,
                            Number = 8,
                            Row = "E"
                        });
                });

            modelBuilder.Entity("WebApplication2.Models.Showtime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CinemaId = 1,
                            MovieId = 1,
                            Time = new DateTime(2025, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CinemaId = 1,
                            MovieId = 1,
                            Time = new DateTime(2025, 5, 10, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CinemaId = 2,
                            MovieId = 1,
                            Time = new DateTime(2025, 5, 10, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CinemaId = 1,
                            MovieId = 2,
                            Time = new DateTime(2025, 5, 10, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CinemaId = 2,
                            MovieId = 2,
                            Time = new DateTime(2025, 5, 10, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CinemaId = 1,
                            MovieId = 3,
                            Time = new DateTime(2025, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CinemaId = 1,
                            MovieId = 1,
                            Time = new DateTime(2025, 5, 10, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApplication2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2025, 5, 9, 10, 46, 2, 68, DateTimeKind.Utc).AddTicks(2989),
                            Email = "admin@cinema.com",
                            FullName = "Admin",
                            IsAdmin = true,
                            PasswordHash = "$2a$11$6G3EHGTWDgvXHA.CnuLjE.cDnirSDmIa2FawDzE8dNVREadwMPWJW",
                            Phone = "0123456789"
                        });
                });

            modelBuilder.Entity("WebApplication2.Models.Booking", b =>
                {
                    b.HasOne("WebApplication2.Models.Showtime", "Showtime")
                        .WithMany()
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("WebApplication2.Models.Seat", b =>
                {
                    b.HasOne("WebApplication2.Models.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("WebApplication2.Models.Showtime", b =>
                {
                    b.HasOne("WebApplication2.Models.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication2.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
